### ISSUE TITLE
Убрать автоматический редирект на лэндинг

### ISSUE THREAD

**Issue by tomarcafe** [GolosChain/tulupchik#34]
сейчас, при открытии любой страницы (кроме static/search.html), пытается загрузить лэндинг. приходится а время пока страничка грузится, куда-то клацать, чтобы переубедить аппу это делать.

причем, иногда бывает ничего-  например открываем главную /, переводит на /landing.html - а бывает и не очень - например открываем /@user/feed - перебрасывает на /@user/landing.html
и не грузит вообще ничего.

**Comment by Undeadlol1** [comment]
Редирект сделан по указу @21xhipster.
Ломающиеся редиректы вроде поправил.
Со статикой возиться смысла не вижу.
